spring.application.name=RssFetcher

server.port=8090

spring.datasource.url=jdbc:postgresql://db:5432/news_monitor_db
spring.datasource.username=admin
spring.datasource.password=admin

rss.worker.enabled=true

spring.main.web-application-type=none
